version: '3'
services:
  dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      - debug=True
    volumes:
      - ./app:/app
